name: Build Gamma

on:
  workflow_call:
    inputs:
      lcd_compiler_version:
        type: string
        required: true

jobs:
  build:
    name: Build Gamma
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: windows-latest
            upload-path: windows/gamma.exe
            upload-name: windows-exe
          - os: ubuntu-latest
            upload-path: linux/gamma
            upload-name: linux-exe
          - os: macOS-latest
            upload-path: macos/gamma
            upload-name: macos-exe

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ inputs.lcd_compiler_version }}
    
    - name: Run build
      run: |
        dub build

    - name: Upload executables
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.upload-name }}
        path: ${{ matrix.upload-path }}
        retention-days: 7

