name: Build Gamma

on:
  workflow_call

jobs:
  build:
    name: Matrix Build Gamma
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ldc-1.33.0
    
    - name: Run build
      run: |
        dub build

