name: Check Gamma project

on:
  workflow_call

jobs:
  check:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-2.103.1
    
    - run: |
        dub fetch dscanner@0.14.0

    - name: Check style
      run: |
        dub run dscanner -- --styleCheck src test
