name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-2.103.1

    - name: Build
      run: |
        dub build --compiler=$DC

    - name: Test
      run: |
        dub test --compiler=$DC --config=example

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-latest

    - run: |
        dub fetch dscanner@0.14.0

    - name: Check Style
      run: |
        dub run dscanner -- --styleCheck src test
