name: CI

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:

  build:
    name: build & test
    uses: ./.github/workflows/build.yml
    with:
      compiler_version: ldc-1.37.0

  check:
    uses: ./.github/workflows/check.yml
    with:
      compiler_version: dmd-2.107.1
