name: CI

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:

  build:
    name: build & test
    uses: ./.github/workflows/build.yml
    with:
      ldc_compiler_version: ldc-1.33.0

  check:
    uses: ./.github/workflows/check.yml
    with:
      dmd_compiler_version: dmd-2.103.1
