name: Build on Push & PR
on: [push, pull_request]

jobs:
  build:
    name: Build Gamma
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-latest
    
    - name: Run build
      run: |
        dub build

  unittest:
    name: Unit Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-latest
    
    - name: Run unit tests
      run: |
        dub test --config=unittest

  test:
    name: Test Gamma
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout source codet
      uses: actions/checkout@v3

    - name: Install D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-latest
    
    - name: Run tests
      run: |
        dub test --config=example

  check:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-latest
    
    - name: Check style
      run: |
        dub fetch dscanner --version=0.12.2
        dub run dscanner -- --styleCheck src test
