name: D
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-latest
    - name: 'Build & Test'
      run: |
        dub build --compiler=$DC
        dub test --compiler=$DC --config=example

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-latest
    - name: 'Check Style'
      run: |
        dub fetch dscanner --version=0.12.2
        dub run dscanner -- --styleCheck src test
