name: Release

on: 
  release:
    types: [published]

jobs:

  build:
    name: build & test
    uses: ./.github/workflows/build.yml
    with:
      ldc_compiler_version: ldc-1.33.0
      gamma_used_dmd_compiler_version: dmd-2.103.1
      build_type: release-gamma

  upload:
    uses: ./.github/workflows/upload.yml
    secrets: inherit
    needs: build
