name: Test Gamma

on:
  workflow_call

jobs:
  test:
    name: Matrix Test Gamma
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-2.103.1
    
    - name: Run tests
      run: |
        dub test --config=example
